### ISSUE TITLE
ICMP.listen()

### ISSUE THREAD

**Issue by anor731** [quantumsheep/node-icmp#6]
```
/home/me/Code/Pong/node_modules/raw-socket/index.js:47
	this.wrap = new raw.SocketWrap (
	            ^

Error: Operation not `permitted
    at new Socket (/home/me/Code/Pong/node_modules/raw-socket/index.js:47:14)
    at Object.exports.createSocket (/home/me/Code/Pong/node_modules/raw-socket/index.js:202:9)
    at new ICMP (/home/me/Code/Pong/node_modules/icmp/index.js:11:27)
    at Function.listen (/home/me/Code/Pong/node_modules/icmp/index.js:149:21)
    at Object.<anonymous> (/home/me/Code/Pong/it.js:2:6)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

```

Maybe the new version of node... I really don't know what does this means.

**Comment by quantumsheep** [comment]
Which system are you on? Could you please give a minimal reproducible code that you're having the issue with?
