### ISSUE TITLE
Error when pinging

### ISSUE THREAD

**Issue by ha6000** [quantumsheep/node-icmp#8]
I get this error when I ping anything
```
Error: Operation not permitted
    at new Socket (/home/harry/dls-issue/node_modules/.pnpm/raw-socket@1.7.0/node_modules/raw-socket/index.js:47:14)
    at Object.exports.createSocket (/home/harry/dls-issue/node_modules/.pnpm/raw-socket@1.7.0/node_modules/raw-socket/index.js:202:9)
    at new ICMP (/home/harry/dls-issue/node_modules/.pnpm/icmp@2.0.1/node_modules/icmp/index.js:11:27)
    at Function.send (/home/harry/dls-issue/node_modules/.pnpm/icmp@2.0.1/node_modules/icmp/index.js:127:21)
    at Function.ping (/home/harry/dls-issue/node_modules/.pnpm/icmp@2.0.1/node_modules/icmp/index.js:138:21)
    at Object.<anonymous> (/home/harry/dls-issue/src/index.js:3:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```
----
OS: Linux Mint 19.3 Tricia
Node: v14.15.4
----

**Comment by ha6000** [comment]
Running with root provides this error
```
internal/modules/cjs/loader.js:1187
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/harry/dls-issue/node_modules/.pnpm/raw-socket@1.7.0/node_modules/raw-socket/build/Release/raw.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/harry/dls-issue/node_modules/.pnpm/raw-socket@1.7.0/node_modules/raw-socket/index.js:4:11)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
```

**Comment by ha6000** [comment]
got it figured out, I had to switch my global node installation to the same as my local nvm one
